---
# tasks file for roles/partition-disk

- set_fact: partition_device="/dev/sda"
  when: ansible_devices.sda is defined 

# TODO: maybe make it so you can set variable which device you want to use than just verify does device exists
# swap can make swap *2 mem size if mem size < 16gb ?
# 1: for now make it simple and just work for single case, later add parameters and more general cases

- name: "Partition disk with sgdisk"
  shell: "sgdisk --clear --new 1:0:+500MiB -c 1:boot --new 2:0:+{{ ( ansible_memtotal_mb * 2 ) | int  }}MiB -c 2:swap --typecode 2:8200 --new 3:0 -c 3:root  --typecode 3:8e00 --print /dev/sda"
  when: ansible_devices.sda is defined 
  register: sgdisk
- name: "Debug: sgdisk"
  debug: var=sgdisk.stdout_lines
